from mythic_container.MythicCommandBase import *
from mythic_container.MythicRPC import *
from container_registry.agent_functions.shared import (
    credential_secrets,
    get_arg_or_build_value,
    get_registry_proto_url,
    redact_sensitive_text,
    resolve_credentials,
    with_authentication_provenance,
)
import asyncio
from tempfile import NamedTemporaryFile


class CopyArguments(TaskArguments):
    def __init__(self, command_line, **kwargs):
        super().__init__(command_line, **kwargs)
        self.args = [
            CommandParameter(
                name="source",
                cli_name="Payload",
                display_name="Payload",
                description="Source payload file",
                type=ParameterType.ChooseOne,
                dynamic_query_function=self.get_payloads,
                parameter_group_info=[ParameterGroupInfo(
                    required=True
                )]
            ),
            CommandParameter(
                name="destination_name",
                type=ParameterType.String,
                description="Destination image name, including the tag, for the configured repository (e.g. alpine:latest)",
                parameter_group_info=[ParameterGroupInfo(
                    required=True
                )]
            ),
            CommandParameter(
                name="DEST_INSECURE",
                type=ParameterType.Boolean,
                description="Allow insecure destination connections",
                parameter_group_info=[ParameterGroupInfo(required=False)],
                default_value=False,
            ),
        ]

    # https://github.com/MythicAgents/Apollo/blob/64946d938bd7328e80807e264081407d6b7f9185/Payload_Type/apollo/apollo/mythic/agent_functions/inject.py#L43-L64
    async def get_payloads(self, inputMsg: PTRPCDynamicQueryFunctionMessage) -> PTRPCDynamicQueryFunctionMessageResponse:
        fileResponse = PTRPCDynamicQueryFunctionMessageResponse(Success=False)
        payload_search = await SendMythicRPCPayloadSearch(MythicRPCPayloadSearchMessage(
            CallbackID=inputMsg.Callback,
            PayloadTypes=["container_wrapper"],
            IncludeAutoGeneratedPayloads=False,
            BuildParameters=[MythicRPCPayloadSearchBuildParameter(PayloadType="container_wrapper")]
        ))

        if payload_search.Success:
            file_names = []
            for f in payload_search.Payloads:
                value = f"{f.Filename} - {f.Description}"
                if value not in file_names:
                    file_names.append(value)
            fileResponse.Success = True
            file_names.reverse()
            fileResponse.Choices = file_names
            return fileResponse
        else:
            fileResponse.Error = payload_search.Error
            return fileResponse

    async def parse_arguments(self):
        if len(self.command_line) == 0:
            raise ValueError("Must supply arguments")
        if self.command_line[0] == "{":
            self.load_args_from_json_string(self.command_line)
        else:
            raise ValueError("Require JSON arguments")


class Copy(CommandBase):
    cmd = "copy"
    needs_admin = False
    help_cmd = "copy (Docker Hub destination: <username>/testing:<tag>)"
    description = "Upload a container wrapper image using callback build credentials, Mythic user secrets, or anonymous access"
    version = 1
    supported_ui_features = ["container_registry:copy"]
    author = "@elreydetoda"
    argument_class = CopyArguments
    attackmapping = []

    async def create_go_tasking(self, taskData: MythicCommandBase.PTTaskMessageAllData) -> MythicCommandBase.PTTaskCreateTaskingMessageResponse:
        response = MythicCommandBase.PTTaskCreateTaskingMessageResponse(
            TaskID=taskData.Task.ID,
            Success=False,
            Completed=True,
        )

        secrets = credential_secrets(taskData)
        resolved_credentials = None
        try:
            # Build skopeo command
            cmd = ["skopeo", "copy"]

            # Add destination authentication if provided
            resolved_credentials = resolve_credentials(taskData)
            if resolved_credentials.pair:
                cmd.extend(
                    [
                        "--dest-creds",
                        f"{resolved_credentials.username}:{resolved_credentials.password}",
                    ]
                )

            dest_insecure = get_arg_or_build_value(taskData, "DEST_INSECURE")
            if dest_insecure:
                cmd.append("--dest-tls-verify=false")

            # https://github.com/MythicAgents/Apollo/blob/64946d938bd7328e80807e264081407d6b7f9185/Payload_Type/apollo/apollo/mythic/agent_functions/inject.py#L141C9-L159
            filename, separator, desc = taskData.args.get_arg("source").partition(" - ")
            if not separator or not filename.strip() or not desc.strip():
                raise ValueError("The selected source payload is invalid")
            filename = filename.strip()
            desc = desc.strip()
            payload_search = await SendMythicRPCPayloadSearch(MythicRPCPayloadSearchMessage(
                CallbackID=taskData.Callback.ID,
                PayloadTypes=["container_wrapper"],
                Filename=filename,
                Description=desc,
                IncludeAutoGeneratedPayloads=False,
                BuildParameters=[MythicRPCPayloadSearchBuildParameter(PayloadType="container_wrapper")]
            ))
            if not payload_search.Success:
                raise RuntimeError("Failed to search for the selected payload")

            if len(payload_search.Payloads) == 0:
                raise RuntimeError("No payload matched the selected source")
            agent_file_id = payload_search.Payloads[0].AgentFileId
            if not agent_file_id:
                raise RuntimeError("The selected payload has no downloadable file")

            payload_contents = await SendMythicRPCFileGetContent(
                MythicRPCFileGetContentMessage(AgentFileID=agent_file_id)
            )
            if not payload_contents.Success:
                raise RuntimeError("Failed to retrieve the selected payload contents")

            with NamedTemporaryFile() as tempFile:
                payload_path = Path(tempFile.name)
            
                payload_path.write_bytes(payload_contents.Content)

                # Add source and destination
                source = f"oci-archive:{payload_path}"
                destination_name = taskData.args.get_arg("destination_name")
                destination = f"{get_registry_proto_url(taskData=taskData,)}/{destination_name}"
                cmd.extend([source, destination])

                # Execute skopeo command
                proc = await asyncio.create_subprocess_exec(
                    *cmd,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )
                stdout, stderr = await proc.communicate()

                # Process output
                if proc.returncode == 0:
                    output = redact_sensitive_text(stdout.decode(errors="replace"), secrets)
                    error_output = redact_sensitive_text(stderr.decode(errors="replace"), secrets)
                    result = f"Successfully copied {source} ({payload_search.Payloads[0].Filename}) to {destination}"
                    if output:
                        result += f"\n\nOutput:\n{output}"
                    if error_output:
                        result += f"\n\nInfo:\n{error_output}"

                    await SendMythicRPCResponseCreate(
                        MythicRPCResponseCreateMessage(
                            TaskID=taskData.Task.ID,
                            Response=with_authentication_provenance(
                                result, resolved_credentials
                            ).encode(),
                        )
                    )
                    response.Success = True
                else:
                    error_msg = redact_sensitive_text(stderr.decode(errors="replace"), secrets)
                    await SendMythicRPCResponseCreate(
                        MythicRPCResponseCreateMessage(
                            TaskID=taskData.Task.ID,
                            Response=with_authentication_provenance(
                                f"Error copying {source} to {destination}:\n{error_msg}",
                                resolved_credentials,
                            ).encode(),
                        )
                    )

        except Exception as e:
            message = f"Exception occurred: {redact_sensitive_text(e, secrets)}"
            if resolved_credentials is not None:
                message = with_authentication_provenance(message, resolved_credentials)
            await SendMythicRPCResponseCreate(
                MythicRPCResponseCreateMessage(
                    TaskID=taskData.Task.ID,
                    Response=message.encode(),
                )
            )

        return response
